---

aws_profile: prod
aws_region: us-east-1

# Below three should be set from command line
kops_cluster_name: k8s.prod.example.com
kops_state_store: s3://kops-cluster-prod-example-com
dns_zone: prod.example.com

ssh_public_key: ~/.ssh/id_rsa_kops.pub
ssh_private_key: ~/.ssh/id_rsa_kops


cloud: aws
zones: us-east-1a,us-east-1b,us-east-1c
node_count: 5
master_count: 3
master_size: t2.medium
node_size: t2.medium
master_volume_size: 10
node_volume_size: 100
bastion: true
bastion_count: 1

networking: kopeio-vxlan
topology: private

# RDS
db_subnet_group: rds-subnet-group
db_identifier: webapp-rds-instance
db_name: csye7125_webapp
db_username: csye7125_user
db_password: Asdf#12345$
allocated_storage: 20

poller_db_name: csye7125_poller
notifier_db_name: csye7125_notifier

# metrics server
metrics_server_file_path: "test_path"

email: "me@example.com"
sub_domain_name: "webapp"